### ISSUE TITLE
Sysaid integration not working consistently, and needs restructuring

### ISSUE THREAD

**Issue by ltwheeler** [dssit/chekhov#57]
Obada reports that the interface for entering 'time to complete entry'  doesn't always work.

Janine suggested the following change - 

currently chekhov is too spammy on sysaid, triggering email notifications whenever a box is checked

instead, it should create ONE activity when the checklist is completed, that uses:
user- the last person to check a box
description- summation of all entries in the checklist
time to complete - summation of all times for each entry in the checklist
since its now one event, the start time would be a bit of a fabrication, and the assigned user somewhat arbitrary

Janine wanted us to collect feedback from the staff to see if there were any differing opinions on which use case would work best

**Comment by cthielen** [comment]
Closing as we no longer use SysAid.
