### ISSUE TITLE
Change completed page to be based on a range of dates

### ISSUE THREAD

**Issue by ltwheeler** [dssit/chekhov#86]
In discussing the interface for completed checklists we ran into the problem of an increasingly large number of completed checklists over the course of the app - as a solution, completed should have 'last 30 days', 'last 90 days', etc. date range filters to distinguish between checklists with the same name

**Comment by cthielen** [comment]
Godo idea. The addition of categories will help also.

What about pagination?

**Comment by ltwheeler** [comment]
We contemplated pagination, but for completed checklists it seems the use case for 'just browsing, dont know which one I want' is limited - over time you'll have hundreds and then thousands of completed checklists, with mostly all the same checklist names so distinguishing one from another will be difficult if you look at the whole pile. 

A pagination of 5000 completed checklists that have non-unique names will be pretty hard to find anything. There is also the eventual performance issue that as the number of completed checklists grows it may become an unsustainable amount of json data, so pagination could help break up those queries.
 
People reaching this page could fall into one of three camps:
1) looking for a specific checklist tied to sysaid (search by sysaid # will likely be the fastest solution)
2) looking for a specific checklist not tied to sysaid
3) looking at checklists generally (date range slices would be more useful to them?)
Adding search by sysaid # will help, and sysaid has a direct link to checklists.

More aggressive filtering options to handle 'started on date', 'completed on date', 'user soandso worked on' may help narrow the results to a volume that browsing would make sense.

Other options would be adding more information on the completed checklists view to try and make it easier to distinguish.

The larger issue for me is, why would someone want to browse completed checklists?
Double checking work on a completed checklist tied to a sysaid ticket makes sense to me, but a view of all completed checklists doesn't help that person, they have a unique identifier to search with that will get them there much faster.

**Comment by retypepassword** [comment]
Completed page? What completed page? (Completed page has been removed and replaced with an in progress/archived button group). There's an option for selecting date ranges in there, though nothing to prevent the user from viewing everything from all time.

**Comment by cthielen** [comment]
I'm a fan of cheeky Eric. Wait, what? :)
